### ISSUE TITLE
Entrega de Requerimientos de Hardware para el Departamento de Infraestructura

### ISSUE THREAD

**Issue by JAGONZAVE** [codice-progressio/zapotlanejo-infrastructura#41]

**Comment by JAGONZAVE** [comment]
[https://app.zenhub.com/files/405209325/a19d0347-126d-4b16-98c1-d9c130ba9851/download](https://app.zenhub.com/files/405209325/a19d0347-126d-4b16-98c1-d9c130ba9851/download)

**Comment by RafaelAngelRamirez** [comment]
Que tal @JAGONZAVE. Me dices tus comentarios sobre esto.

# Propuesta para Equipo de desarrollo

> ASUS Portátil - Chromebook C436FA C436FA-i716g128CO-01
> (14") - FHD 1920 x 1080 - Glossy - Touch screen - Core i7 (10
> Gen) i7-10510U 1.8 GHz - Intel UHD Graphics - 16GB RAM -
> 128GB SSD - Gris - Chrome - FingerPrint - 42WHrs.
> P/N: C436FA-I716G128CO-01


## Justificación

- Se requiere un equipo que mantenga levantados multiples servidores. 
- El mínimo de carga de ram es de 8Gb para las aplicaciones que se requiere desarrollar. 
- Multiples sistemas operativos virtualizados para mantener el flujo de trabajo entre desarrollo y produccion ( WSL 2 )
- Gran capacidad de procesamiento para compilaciones continuas. 


# Propuesta equipo infrastructura

> Lenovo Portátil - Lenovo ThinkBook 13s G2 ITL 20V9006XLM
> Robusto 33.8cm (13.3") - WQXGA - 2560 x 1600 - Intel Core i5
> (11a generación) i5-1135G7 Quad-core (4 Core) 2.40GHz - 8GB
> RAM - 256GB SSD - Gris - Intel SoC - Windows 10 Pro - Intel
> Iris Xe Graphics - Tecnología conmutación en el mismo plano
> (In-plane Switching, IPS) - Español Teclado - IEEE 802.11ax
> Wireless LAN Standard


## Justificación

- Equipo robusto para movilizarlo para dar soporte en sitio o en exteriores. 
- Multitarea para permitir cambiar entre diferentes actividades sin caída en la productividad.

**Comment by JAGONZAVE** [comment]
@RafaelAngelRamirez Rafa esta quedara descartada pues su sistema operativo es Chrome OS y requerimos mas bien Windows y/o Linux

> ASUS Portátil - Chromebook C436FA C436FA-i716g128CO-01
> (14") - FHD 1920 x 1080 - Glossy - Touch screen - Core i7 (10
> Gen) i7-10510U 1.8 GHz - Intel UHD Graphics - 16GB RAM -
> 128GB SSD - Gris - Chrome - FingerPrint - 42WHrs.
> P/N: C436FA-I716G128CO-01

**Comment by RafaelAngelRamirez** [comment]
@JAGONZAVE No lo había visto. Me deje llevar por el hardware. En este caso esta es mi alternativa. 

> ## HP INC HP ProBook 440 G8,Intel® Core™ i7-1165G7
> Windows® 10 Pro 64bit, No, WLAN IWiFi6AX201ax2x2MUMIMOnvP160MHz+BT, No WWAN, 8 GB, 8
> GB (1x8GB) DDR4 3200, SSD 256 GB, No, No, BATT 3C 45
> WHr Long Life, LCD 14, LCD 14 HD AG LED SVA 250 fHDC
> NWBZ bent, No, No, No DIB, 1/1/0, HD, Spill-Resistant, Click
> Pad, Yes FPS

En este caso hay que agregar un modulo de memoria más para cubrir 16GB. Las otras dos propuestas no cumplen con este requisito que será determinante para el buen desempeño.
